version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: 'fiora-nest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodb_data:
